### ISSUE TITLE
NAPI in snull is broken

### ISSUE THREAD

**Issue by danjurgens** [martinezjavier/ldd3#18]
```
if (use_napi) {
    netif_napi_add(dev, &priv->napi, snull_poll,2);
}
memset(priv, 0, sizeof(struct snull_priv));
```

This code promptly erases the NAPI setup after adding it.  As a result the poll never gets called after the interrupt handler calls napi_schedule.

**Comment by dwalkes** [comment]
This code is still there, however I haven't tried snull myself so I can't confirm whether this is indeed an issue.  If it is for anyone please submit a PR.

**Comment by dwalkes** [comment]
@jypan-ccu since you've recently tested this with #41  - did you find this to be an issue?

**Comment by jypan-ccu** [comment]
I have patched this, but I  don't know how to put on the git. Is pull request again or ?

**Comment by dwalkes** [comment]
Thanks @jypan-ccu I've merged with https://github.com/martinezjavier/ldd3/pull/53
