### ISSUE TITLE
Bug in file short.c

### ISSUE THREAD

**Issue by dovnmr** [martinezjavier/ldd3#2]
function called with argument short_base:
 release_mem_region(short_base, SHORT_NR_PORTS) 
but value not exist after call to iounmap()
it should use base variable in place of it:
release_mem_region(base, SHORT_NR_PORTS) 

If you will call following command you will get crash
cat /proc/iomem

**Comment by dwalkes** [comment]
This should be addressed with https://github.com/martinezjavier/ldd3/pull/53 with thanks to  @jypan-ccu  - please re-open if the problem still exists.
