### ISSUE TITLE
proc interface has changed

### ISSUE THREAD

**Issue by Cat22** [martinezjavier/ldd3#23]
The proc interface has changed and create_proc_entry is outdated. It will not compile under the 4.7.5 kernel, use proc_create instead  (see proc_fs.h)

ldd3/misc-modules/seq.c: In function ‘ct_init’:
ldd3/misc-modules/seq.c:97:2: error: implicit declaration of function ‘create_proc_entry’ [-Werror=implicit-function-declaration]
  entry = create_proc_entry("sequence", 0, NULL);
  ^
ldd3/misc-modules/seq.c:97:8: warning: assignment makes pointer from integer without a cast [enabled by default]
  entry = create_proc_entry("sequence", 0, NULL);
        ^
ldd3/misc-modules/seq.c:99:8: error: dereferencing pointer to incomplete type
   entry->proc_fops = &ct_file_ops;

**Comment by dwalkes** [comment]
Please re-open if this is still an issue with latest code
