### ISSUE TITLE
make dep doesn't work!

### ISSUE THREAD

**Issue by MiterV1** [martinezjavier/ldd3#25]
Hi guys!
    I want to test the function of make dep,but it doesn't work properly.That's the log information.

# uname -r
4.4.0-94-generic

# pwd
/home/xxx/ldd3-examples-3.x/scull

# make dep
cc -O2 -M *.c > .depend
access.c:21:26: fatal error: linux/module.h: No such file or directory
compilation terminated.
main.c:17:26: fatal error: linux/module.h: No such file or directory
compilation terminated.
pipe.c:17:26: fatal error: linux/module.h: No such file or directory
compilation terminated.
scull.mod.c:1:26: fatal error: linux/module.h: No such file or directory
compilation terminated.
Makefile:38: recipe for target 'dep' failed
make: *** [dep] Error 1

# git branch
* (HEAD detached at v4.4)
  master

**Comment by dwalkes** [comment]
Please re-open if this is still an issue with latest code.
