### ISSUE TITLE
driver scullpipe

### ISSUE THREAD

**Issue by zyc737347123** [martinezjavier/ldd3#26]
scullpipe0-3, don't work after successfully run the command "scull.init start".
And then i find , the minor of scullpipe0-3 is 4-7 in scull_load shell, but the minor of scullpipe0-3 is 32~35 in scull.init shell. 
error minor number is the reason.

**Comment by dwalkes** [comment]
scullpipe is working on latest builds I believe, please re-open if this is still an issue.
