### ISSUE TITLE
build error:  arch/x86/Makefile:153: CONFIG_X86_X32 enabled but no binutils support

### ISSUE THREAD

**Issue by leeehui** [martinezjavier/ldd3#28]
Hi,
I just met build error with the following message. 
Note that I have cross compile binary for aarch64 under my Download dir, but I remove the dir from PATH
I wonder how to avoid this problem, thanks.

make -C /lib/modules/4.13.0-37-generic/build M=/home/lihui/ldd3/scull modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-37-generic'
arch/x86/Makefile:153: CONFIG_X86_X32 enabled but no binutils support
./scripts/gcc-version.sh: line 25: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: No such file or directory
./scripts/gcc-version.sh: line 26: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: No such file or directory
make[1]: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: Command not found
make[1]: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: Command not found
make[1]: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: Command not found
make[1]: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: Command not found
make[1]: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: Command not found
  CC [M]  /home/lihui/ldd3/scull/main.o
/bin/sh: 1: /home/lihui/Downloads/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-elf/bingcc: not found
scripts/Makefile.build:308: recipe for target '/home/lihui/ldd3/scull/main.o' failed
make[2]: *** [/home/lihui/ldd3/scull/main.o] Error 127
Makefile:1550: recipe for target '_module_/home/lihui/ldd3/scull' failed
make[1]: *** [_module_/home/lihui/ldd3/scull] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-37-generic'
Makefile:30: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by dwalkes** [comment]
Sorry I didn't see this earlier, I expect you aren't still having problems with this but if so please comment and I can help with suggestions about cross compile setup.
