### ISSUE TITLE
Is the assignment operation is redundant？

### ISSUE THREAD

**Issue by liyangorg** [martinezjavier/ldd3#33]
https://github.com/martinezjavier/ldd3/blob/bdf0647e57c8319cf5ce90375891c173b8f5d63f/scull/main.c#L607

Hi, martinezjavier.

The assignment operation: "dev->cdev.ops = &scull_fops;", already included in function cdev_init,  whether in v2.6.12 or in v5.1-rc4.

_so, the assignment is redundant?_ 

The following code is taken from :
https://github.com/torvalds/linux/blob/master/fs/char_dev.c 
v5.1-rc4 
```
/**
 * cdev_init() - initialize a cdev structure
 * @cdev: the structure to initialize
 * @fops: the file_operations for this device
 *
 * Initializes @cdev, remembering @fops, making it ready to add to the
 * system with cdev_add().
 */
void cdev_init(struct cdev *cdev, const struct file_operations *fops)
{
	memset(cdev, 0, sizeof *cdev);
	INIT_LIST_HEAD(&cdev->list);
	kobject_init(&cdev->kobj, &ktype_cdev_default);
	cdev->ops = fops;
}
```

**Comment by dwalkes** [comment]
> so, the assignment is redundant?

I believe so!  Fixed in https://github.com/martinezjavier/ldd3/pull/48
