### ISSUE TITLE
Recent change in signature of netdevice.h/ndo_tx_timeout

### ISSUE THREAD

**Issue by AlfredTH** [martinezjavier/ldd3#42]
Hi and thanks for maintaining these files up to date :)
While trying to compile snull, I encountered an issue with the signature of ndo_tx_timeout:
```
error: initialization of ‘void (*)(struct net_device *, unsigned int)’ from incompatible pointer type ‘void (*)(struct net_device *)’ [-Werror=incompatible-pointer-types]
  638 |  .ndo_tx_timeout      = snull_tx_timeout
```
This is correct according to the linux repo, and to my up-to-date arch linux machine.
Here is the specific line including the new definition:
https://github.com/torvalds/linux/blob/master/include/linux/netdevice.h#L1030
The change seems to have been included in this commit:
https://github.com/torvalds/linux/commit/0290bd291cc0e0488e35e66bf39efcd7d9d9122b

Many thanks for your time.

**Comment by dwalkes** [comment]
Thanks @AlfredTH for tracking down this commit and change.
I haven't tried with 5.6+ kernels yet but if you'd like to take a crack at this yourself and submit a pull request please do.  I think the change will be pretty simple.
You can see from the [commit you linked](https://github.com/torvalds/linux/commit/0290bd291cc0e0488e35e66bf39efcd7d9d9122b) that the change went into kernels starting with 5.6:
![image](https://user-images.githubusercontent.com/227565/80867647-86808d00-8c52-11ea-9f0d-a26c2407ecf8.png)
So what you can do in code [here](https://github.com/martinezjavier/ldd3/blob/13a7786cb8506dc2c8458f6848fa612e48d4ec3f/snull/snull.c#L93) and [here](https://github.com/martinezjavier/ldd3/blob/13a7786cb8506dc2c8458f6848fa612e48d4ec3f/snull/snull.c#L537) is to add a code block that looks like this:
```
#if LINUX_VERSION_CODE < KERNEL_VERSION(5,6,0)
    static void snull_tx_timeout(struct net_device *dev);
#else 
    static void snull_tx_timeout(struct net_device *dev, unsigned int txqueue);
#endif 
```
and do the same for the definition.
This should get you past this particular compile error.  Assuming it does please create a PR for the change and I'll approve it.
Eventually we should probably come up with a single place to handle these deviations so we don't have them scattered througout the code and some documentation for contributors about how to handle this.  I'll think about the best way to do this.

**Comment by dwalkes** [comment]
I believe this is now resolved, please re-open if not
