### ISSUE TITLE
Scull device number cleanup unregistering wrong major

### ISSUE THREAD

**Issue by eltonlaw** [martinezjavier/ldd3#44]
Maybe I'm wrong (or it's an explicit omission, I haven't finished the book yet), but I think there is a bug with the example code in `scull/main.c`.

When doing cleanup, `unregister_chrdev_region` https://github.com/martinezjavier/ldd3/blob/13a7786cb8506dc2c8458f6848fa612e48d4ec3f/scull/main.c#L590 is called on `devno` set at https://github.com/martinezjavier/ldd3/blob/13a7786cb8506dc2c8458f6848fa612e48d4ec3f/scull/main.c#L574 which is creating this with the parameters from the header. That covers one of the branchs of the if but in the case where we're dynamically allocating the major device number https://github.com/martinezjavier/ldd3/blob/13a7786cb8506dc2c8458f6848fa612e48d4ec3f/scull/main.c#L628-L632 there would be a mismatch I think.

I solved this by just initializing a global `dev_t`.

**Comment by dwalkes** [comment]
@eltonlaw thanks for your comment.  I took a quick look.

> but in the case where we're dynamically allocating the major device number there would be a mismatch I think.

It looks like `alloc_chrdev_region` just calls `__register_chrdrv_region` with a 0 for major number.
https://github.com/torvalds/linux/blob/f359287765c04711ff54fbd11645271d8e5ff763/fs/char_dev.c#L236-L245 

The `register_chrdev_region` function calls the same `__register_chrdrv_region` but provides major/minor numbers.
https://github.com/torvalds/linux/blob/f359287765c04711ff54fbd11645271d8e5ff763/fs/char_dev.c#L200-L223

Regardless of whether the major number is specified or [dynamically found](https://github.com/torvalds/linux/blob/f359287765c04711ff54fbd11645271d8e5ff763/fs/char_dev.c#L122-L130)  the logic in `__register_chrdev_region` just looks to make sure there's no overlap with current defined device numbers and doesn't do anything special for the case the major number was dynamically found.

https://github.com/torvalds/linux/blob/f359287765c04711ff54fbd11645271d8e5ff763/fs/char_dev.c#L134-L148

So it looks to me like either of the if branches would be handled correctly with `unregister_chrdev_region`.  Let me know if I've misunderstood your comments.

**Comment by eltonlaw** [comment]
Thanks for the reply. Ah, I hadn't looked at the implementation of `alloc_chrdev_region`, my bad, should've done that first.

I think the point remains though, that the dynamically found path doesn't work. `_register_ chrdrv_region` has some logic that if `major` is 0 it sets major to the value of `find_dynamic_major()` https://github.com/torvalds/linux/blob/f359287765c04711ff54fbd11645271d8e5ff763/fs/char_dev.c#L122-L130 . `find_dynamic_major` doesn't seem to always return 0 as it'll return the last index of `chrdevs` plus one... something something free number among the available to pick from.

**Comment by dwalkes** [comment]
> that the dynamically found path doesn't work

I don't think I understand what you mean by this.  Are you seeing some problem when you run the example?  Which path are you referring to?

> `find_dynamic_major` doesn't seem to always return 0

I don't see how `find_dynamic_major` would ever return 0.  I think it's always going to return the first available unused major which can be allocated for use by the driver, or `-EBUSY` if none can be allocated.

**Comment by eltonlaw** [comment]
Ah crap, nevermind. I bungled it. I completely missed the one line

```
         scull_major = MAJOR(dev);
```

inside the init module, my bad, I had thought that the unregister was being called on the wrong major `0`, as set in the default. Whoops. Everything works. Thanks for the reply, sorry for the waste of time.

**Comment by dwalkes** [comment]
> sorry for the waste of time.

No worries!
