### ISSUE TITLE
sbull is still obsolete, not able to compile on 5.x linux kernel versions

### ISSUE THREAD

**Issue by deepakbabel23** [martinezjavier/ldd3#50]
Hi @martinezjavier,
It seems that scull and other device drivers code was updated to work with latest linux kernel version, but sbull code is still obsolete. Is someone going to fix it anytime soon? It would be very helpful for newbies like me to understand working sbull code, to understand concepts like block tracking and block device internals.

**Comment by jypan-ccu** [comment]
Hi, try this branch
https://github.com/martinezjavier/ldd3/tree/jypan-ccu-update_snull%2Bfixes
I have patched sbull code and tested on linux kernel 5.8 version.
RM_SIMPLE, RM_FULL, RM_NOQUEUE all work.

null_blk is also a good example although it's larger.
It is native insides Linux kernel source with some documents.

I still prefer LDD3 examples.

**Comment by deepakbabel23** [comment]
Hi @martinezjavier ,
I tried it now on my ubuntu 18 with Linux kernel 5.4.x. It still fails to build. I can paste the log here for your reference:
`2:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:107:16: error: implicit declaration of function ‘blk_fetch_request’; did you mean ‘blk_get_request’? [-Werror=implicit-function-declaration]
9:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:109:10: error: ‘struct request’ has no member named ‘cmd_type’
12:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:109:24: error: ‘REQ_TYPE_FS’ undeclared (first use in this function); did you mean ‘DESCTYPE_S’?
17:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:111:4: error: implicit declaration of function ‘__blk_end_request_cur’; did you mean ‘blk_get_request’? [-Werror=implicit-function-declaration]
21:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:119:8: error: ‘struct request’ has no member named ‘buffer’
25:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:132:25: error: ‘struct bio’ has no member named ‘bi_sector’; did you mean ‘bi_next’?
31:./include/linux/bio.h:154:12: error: incompatible types when assigning to type ‘int’ from type ‘struct bvec_iter’
40:./include/linux/bio.h:155:13: error: request for member ‘bi_size’ in something not a structure or union
52:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
76:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
103:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
130:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
175:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
223:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
268:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
316:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
367:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
415:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
457:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
502:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
544:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
586:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
631:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
673:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
715:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
757:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
802:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
844:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
889:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
931:./include/linux/kernel.h:866:2: error: first argument to ‘__builtin_choose_expr’ not a constant
970:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1009:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
1045:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
1093:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1144:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
1192:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
1243:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1297:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
1348:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
1393:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1441:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
1486:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
1531:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1579:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
1624:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
1669:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
1714:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1762:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
1807:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1855:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
1900:./include/linux/kernel.h:866:2: error: first argument to ‘__builtin_choose_expr’ not a constant
1942:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
1984:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2023:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
2065:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2110:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2152:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
2197:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2245:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2290:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
2329:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2371:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2410:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
2449:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2491:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2530:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
2569:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
2608:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2650:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2689:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2731:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2770:./include/linux/kernel.h:866:2: error: first argument to ‘__builtin_choose_expr’ not a constant
2806:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2842:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
2875:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
2917:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
2962:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3004:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
3049:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3097:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3142:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
3181:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3223:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3262:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
3301:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3343:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3382:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
3421:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
3460:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3502:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3541:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3583:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3622:./include/linux/kernel.h:866:2: error: first argument to ‘__builtin_choose_expr’ not a constant
3658:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3694:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3727:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
3769:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3814:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3856:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
3901:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
3949:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
3994:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4033:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4075:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
4114:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4153:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4195:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
4234:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4273:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4312:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4354:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
4393:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4435:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
4474:./include/linux/kernel.h:866:2: error: first argument to ‘__builtin_choose_expr’ not a constant
4510:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4552:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4597:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
4639:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4684:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4732:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
4777:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4816:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4858:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
4897:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
4936:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
4978:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
5017:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
5056:./include/linux/bvec.h:52:12: error: request for member ‘bi_size’ in something not a structure or union
5095:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
5137:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
5176:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
5218:./include/linux/bvec.h:53:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
5257:./include/linux/kernel.h:866:2: error: first argument to ‘__builtin_choose_expr’ not a constant
5293:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
5329:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
5362:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
5398:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
5431:./include/linux/kernel.h:866:2: error: first argument to ‘__builtin_choose_expr’ not a constant
5458:./include/linux/bvec.h:45:53: error: request for member ‘bi_idx’ in something not a structure or union
5482:./include/linux/bvec.h:56:55: error: request for member ‘bi_bvec_done’ in something not a structure or union
5514:./include/linux/bio.h:157:45: error: ‘bvec’ is a pointer; did you mean to use ‘->’?
5523:./include/linux/bio.h:157:31: error: passing argument 2 of ‘bio_advance_iter’ from incompatible pointer type [-Werror=incompatible-pointer-types]
5535:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:136:18: error: implicit declaration of function ‘__bio_kmap_atomic’; did you mean ‘__kunmap_atomic’? [-Werror=implicit-function-declaration]
5539:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:136:44: error: ‘KM_USER0’ undeclared (first use in this function); did you mean ‘SI_USER’?
5543:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:140:3: error: implicit declaration of function ‘__bio_kunmap_atomic’; did you mean ‘__kunmap_atomic’? [-Werror=implicit-function-declaration]
5548:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:155:17: error: ‘struct bio’ has no member named ‘bi_size’; did you mean ‘bi_disk’?
5556:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:172:10: error: ‘struct request’ has no member named ‘cmd_type’
5559:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:172:24: error: ‘REQ_TYPE_FS’ undeclared (first use in this function); did you mean ‘DESCTYPE_S’?
5563:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:174:4: error: implicit declaration of function ‘__blk_end_request’; did you mean ‘blk_get_request’? [-Werror=implicit-function-declaration]
5568:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:193:2: error: too many arguments to function ‘bio_endio’
5577:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:337:2: error: implicit declaration of function ‘init_timer’; did you mean ‘init_timers’? [-Werror=implicit-function-declaration]
5581:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:338:12: error: ‘struct timer_list’ has no member named ‘data’
5584:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:339:22: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
5587:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:350:38: error: passing argument 2 of ‘blk_queue_make_request’ from incompatible pointer type [-Werror=incompatible-pointer-types]
5594:/home/deepak/projects/ldd3_sbull_bugfixes/ldd3/sbull/sbull.c:354:16: error: implicit declaration of function ‘blk_init_queue’; did you mean ‘blk_put_queue’? [-Werror=implicit-function-declaration]
`

Thank you for your quick response. Its my first few days of learning block device driver and documentation is not much for 5.x kernel device drivers especially block device drivers. I am interested in understanding CBT and copy on write for incremental backup.
Deepak

**Comment by deepakbabel23** [comment]
Hi @martinezjavier ,
Yes it is working fine now. Sorry for my previous comment, I was on 'master' branch. Just checked out your bug-fixes branch and it worked like a charm.

Thanks much.

**Comment by dwalkes** [comment]
Merged to master with https://github.com/martinezjavier/ldd3/pull/51

**Comment by deepakbabel** [comment]
Hi,
One quick question. Also are there any updated documentation guide?
