### ISSUE TITLE
kernel panic generation when i run "insmod snull.ko" at 4.19.94-ti-r50

### ISSUE THREAD

**Issue by jisu5619** [martinezjavier/ldd3#55]
sudo insmod snull.ko 

 I have a kernel panic when i run sudo insmod snull.ko. at Beaglbone AI (  4.19.94-ti-r50)

i have kernel panic 
I use 4.19.94-ti-r50 at Beaglebone AI  
 

root@beaglebone:/home/debian/LDD/snull# sudo insmod snull.ko
root@beaglebone:/home/debian/LDD/snull# [ 4026.234112] Pool empty
[ 4027.008435] ------------[ cut here ]------------
[ 4027.013118] WARNING: CPU: 0 PID: 0 at net/sched/sch_generic.c:466 dev_watchdog+0x258/0x25c
[ 4027.021453] NETDEV WATCHDOG: sn0 (): transmit queue 0 timed out
[ 4027.027421] Modules linked in: snull(O) sbull(O+) hello_1(O) xt_state xt_conntrack nft_counter nft_chain_nat_ipv4 ipt_MASQUERADE nft_compat pru_rproc irq_pruss_intc rpmsg_rpc pruss bnep virtio_rpmsg_bus uio_pruss_shmem pruss_soc_bus ti_vip ti_vpe btsdio ti_sc videobuf2_dma_contig ti_csc bluetooth ti_vpdma v4l2_fwnode v4l2_mem2mem v4l2_common videobuf2_memops videobuf2_v4l2 videobuf2_common videodev media ecdh_generic brcmfmac brcmutil cfg80211 omap_remoteproc remoteproc virtio virtio_ring usb_f_ncm usb_f_mass_storage usb_f_rndis u_ether libcomposite uio_pdrv_genirq uio gpio_pisosr spidev [last unloaded: snull]
[ 4027.081808] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G      D W  O      4.19.94-ti-r50 #1buster
[ 4027.090371] Hardware name: Generic DRA74X (Flattened Device Tree)
[ 4027.096513] [<c0113e18>] (unwind_backtrace) from [<c010e388>] (show_stack+0x20/0x24)
[ 4027.104299] [<c010e388>] (show_stack) from [<c0d285fc>] (dump_stack+0x8c/0xa0)
[ 4027.111562] [<c0d285fc>] (dump_stack) from [<c013c928>] (__warn.part.3+0xcc/0xe8)
[ 4027.119085] [<c013c928>] (__warn.part.3) from [<c013c9bc>] (warn_slowpath_fmt+0x78/0x94)
[ 4027.127217] [<c013c9bc>] (warn_slowpath_fmt) from [<c0babe24>] (dev_watchdog+0x258/0x25c)
[ 4027.135439] [<c0babe24>] (dev_watchdog) from [<c01ca238>] (call_timer_fn+0x3c/0x210)
[ 4027.143222] [<c01ca238>] (call_timer_fn) from [<c01ca4d8>] (expire_timers+0xcc/0x174)
[ 4027.151090] [<c01ca4d8>] (expire_timers) from [<c01ca63c>] (run_timer_softirq+0xbc/0x1bc)
[ 4027.159308] [<c01ca63c>] (run_timer_softirq) from [<c010250c>] (__do_softirq+0x16c/0x438)
[ 4027.167529] [<c010250c>] (__do_softirq) from [<c0143cbc>] (irq_exit+0xd8/0xec)
[ 4027.174792] [<c0143cbc>] (irq_exit) from [<c01adecc>] (__handle_domain_irq+0x90/0xfc)
[ 4027.182663] [<c01adecc>] (__handle_domain_irq) from [<c0102364>] (gic_handle_irq+0x4c/0x88)
[ 4027.191054] [<c0102364>] (gic_handle_irq) from [<c0101a0c>] (__irq_svc+0x6c/0xa8)
[ 4027.198569] Exception stack(0xc1501ed8 to 0xc1501f20)
[ 4027.203644] 1ec0:                                                       00000000 007c7460
[ 4027.211861] 1ee0: fe600000 00000000 ffffe000 c1506e34 c1506e7c 00000001 00000001 c15de2ba
[ 4027.220078] 1f00: c10e6414 c1501f34 c1501f14 c1501f28 c012cdd4 c010a6f4 60010013 ffffffff
[ 4027.228297] [<c0101a0c>] (__irq_svc) from [<c010a6f4>] (arch_cpu_idle+0x30/0x4c)
[ 4027.235732] [<c010a6f4>] (arch_cpu_idle) from [<c0d446ec>] (default_idle_call+0x38/0x3c)
[ 4027.243863] [<c0d446ec>] (default_idle_call) from [<c0172b30>] (do_idle+0x11c/0x158)
[ 4027.251643] [<c0172b30>] (do_idle) from [<c0172e68>] (cpu_startup_entry+0x28/0x30)
[ 4027.259251] [<c0172e68>] (cpu_startup_entry) from [<c0d3db08>] (rest_init+0xd4/0xd8)
[ 4027.267036] [<c0d3db08>] (rest_init) from [<c1401004>] (start_kernel+0x490/0x4c0)
[ 4027.274579] ---[ end trace 0152fed7b0e69663 ]---
[ 4027.279905] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[ 4027.288098] pgd = 2f826f0f
[ 4027.290843] [00000000] *pgd=00000000
[ 4027.294466] Internal error: Oops: 5 [#2] PREEMPT SMP ARM
[ 4027.299804] Modules linked in: snull(O) sbull(O+) hello_1(O) xt_state xt_conntrack nft_counter nft_chain_nat_ipv4 ipt_MASQUERADE nft_compat pru_rproc irq_pruss_intc rpmsg_rpc pruss bnep virtio_rpmsg_bus uio_pruss_shmem pruss_soc_bus ti_vip ti_vpe btsdio ti_sc videobuf2_dma_contig ti_csc bluetooth ti_vpdma v4l2_fwnode v4l2_mem2mem v4l2_common videobuf2_memops videobuf2_v4l2 videobuf2_common videodev media ecdh_generic brcmfmac brcmutil cfg80211 omap_remoteproc remoteproc virtio virtio_ring usb_f_ncm usb_f_mass_storage usb_f_rndis u_ether libcomposite uio_pdrv_genirq uio gpio_pisosr spidev [last unloaded: snull]
[ 4027.354148] CPU: 0 PID: 9 Comm: ksoftirqd/0 Tainted: G      D W  O      4.19.94-ti-r50 #1buster
[ 4027.362884] Hardware name: Generic DRA74X (Flattened Device Tree)
[ 4027.369016] PC is at snull_tx+0xf4/0x234 [snull]
[ 4027.373660] LR is at dev_hard_start_xmit+0xd4/0x2cc
[ 4027.378560] pc : [<bf7b5448>]    lr : [<c0b6a92c>]    psr: 000f0013
[ 4027.384854] sp : d4197d28  ip : 00000000  fp : d4197d9c
[ 4027.390102] r10: 00000000  r9 : bf7b7280  r8 : 0000006e
[ 4027.395349] r7 : 0000006e  r6 : c1506e08  r5 : d1cdf800  r4 : d1ce6002
[ 4027.401905] r3 : 00000020  r2 : d1cdf800  r1 : 6674692a  r0 : 000002ff
[ 4027.408462] Flags: nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[ 4027.415629] Control: 10c5387d  Table: 9196806a  DAC: 00000051
[ 4027.421401] Process ksoftirqd/0 (pid: 9, stack limit = 0xf5db9d5e)
[ 4027.427609] Stack: (0xd4197d28 to 0xd4198000)
[ 4027.431988] 7d20:                   00000400 00000000 0000002a 00000400 000002aa 00000400
[ 4027.440204] 7d40: d4197d6c c0b6a16c 00004008 d18c0240 00000000 c1506e08 00000000 c0b6a4a0
[ 4027.448421] 7d60: d4197d9c d4197d70 c0b6a16c 7d8a13bb 00000000 d18c0240 d1cdf800 c1506e08
[ 4027.456638] 7d80: 00000000 00000000 d1cdf800 d0af0a00 d4197dfc d4197da0 c0b6a92c bf7b5360
[ 4027.464855] 7da0: d4197e07 d1cdf800 d4197dcc d4197e08 00000000 c15e3b60 c1504d00 c15e3b78
[ 4027.473072] 7dc0: c1506e34 c1508544 0000006e ffffe000 c1506e08 d41f0800 d18c0240 c1506e08
[ 4027.481289] 7de0: 00000000 d0af0a00 d1cdf800 00000000 d4197e3c d4197e00 c0bac180 c0b6a864
[ 4027.489506] 7e00: c0731668 00731528 00000010 7d8a13bb c0bab410 d41f0800 d18c0240 00000001
[ 4027.497721] 7e20: ffffff92 d0af0a00 d18c0240 00000001 d4197e8c d4197e40 c0bac60c c0bac070
[ 4027.505938] 7e40: 00000000 00000001 c15e3938 c1506e34 d41f088c d41f0840 ffffe000 00000040
[ 4027.514154] 7e60: dff14640 d41f0800 d2377c00 dff14640 00000000 00000100 000000a1 00000000
[ 4027.522370] 7e80: d4197ec4 d4197e90 c0b66804 c0bac4ac d4197ec4 c111b97c 00000008 00000002
[ 4027.530586] 7ea0: 00000001 c1504088 ffffe000 00000100 000000a1 00000000 d4197f2c d4197ec8
[ 4027.538803] 7ec0: c010250c c0b666cc c1506e08 c1507478 c0e03f78 04208040 c1504d00 000e37ec
[ 4027.547020] 7ee0: c1138158 0000000a c14cd6c0 c15de8f8 c1506e34 c11cf598 c14c5358 c1504080
[ 4027.555237] 7f00: ffffe000 ffffe000 d415f740 c15232c4 c1506e08 00000001 00000000 00000000
[ 4027.563454] 7f20: d4197f3c d4197f30 c01439c0 c01023ac d4197f74 d4197f40 c0165090 c0143984
[ 4027.571669] 7f40: d4197f74 7d8a13bb c015ffb0 d415f700 d415f780 00000000 d4196000 d415f740
[ 4027.579885] 7f60: c0164ea8 d4163dd4 d4197fac d4197f78 c01604c0 c0164eb4 d415f71c d415f71c
[ 4027.588100] 7f80: 00000000 d415f780 c0160354 00000000 00000000 00000000 00000000 00000000
[ 4027.596317] 7fa0: 00000000 d4197fb0 c01010e8 c0160360 00000000 00000000 00000000 00000000
[ 4027.604533] 7fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 4027.612749] 7fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[ 4027.620996] [<bf7b5448>] (snull_tx [snull]) from [<c0b6a92c>] (dev_hard_start_xmit+0xd4/0x2cc)
[ 4027.629654] [<c0b6a92c>] (dev_hard_start_xmit) from [<c0bac180>] (sch_direct_xmit+0x11c/0x43c)
[ 4027.638309] [<c0bac180>] (sch_direct_xmit) from [<c0bac60c>] (__qdisc_run+0x16c/0x5e8)
[ 4027.646264] [<c0bac60c>] (__qdisc_run) from [<c0b66804>] (net_tx_action+0x144/0x304)
[ 4027.654047] [<c0b66804>] (net_tx_action) from [<c010250c>] (__do_softirq+0x16c/0x438)
[ 4027.661917] [<c010250c>] (__do_softirq) from [<c01439c0>] (run_ksoftirqd+0x48/0x50)
[ 4027.669619] [<c01439c0>] (run_ksoftirqd) from [<c0165090>] (smpboot_thread_fn+0x1e8/0x2fc)
[ 4027.677926] [<c0165090>] (smpboot_thread_fn) from [<c01604c0>] (kthread+0x16c/0x174)
[ 4027.685706] [<c01604c0>] (kthread) from [<c01010e8>] (ret_from_fork+0x14/0x2c)
[ 4027.692959] Exception stack(0xd4197fb0 to 0xd4197ff8)
[ 4027.698035] 7fa0:                                     00000000 00000000 00000000 00000000
[ 4027.706251] 7fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 4027.714466] 7fe0: 00000000 00000000 00000000 00000000 00000013 00000000
[ 4027.721115] Code: e1c431b8 e0423005 e595a5e0 e16f3f13 (e59a2000)
[ 4027.727289] ---[ end trace 0152fed7b0e69664 ]---
[ 4027.731960] Kernel panic - not syncing: Fatal exception in interrupt
[ 4027.738354] CPU1: stopping
[ 4027.741081] CPU: 1 PID: 856 Comm: systemd-journal Tainted: G      D W  O      4.19.94-ti-r50 #1buster
[ 4027.750342] Hardware name: Generic DRA74X (Flattened Device Tree)
[ 4027.756479] [<c0113e18>] (unwind_backtrace) from [<c010e388>] (show_stack+0x20/0x24)
[ 4027.764265] [<c010e388>] (show_stack) from [<c0d285fc>] (dump_stack+0x8c/0xa0)
[ 4027.771527] [<c0d285fc>] (dump_stack) from [<c0111b70>] (handle_IPI+0x3f4/0x420)
[ 4027.778962] [<c0111b70>] (handle_IPI) from [<c010239c>] (gic_handle_irq+0x84/0x88)
[ 4027.786569] [<c010239c>] (gic_handle_irq) from [<c0101e14>] (__irq_usr+0x54/0x80)
[ 4027.794085] Exception stack(0xd23a7fb0 to 0xd23a7ff8)
[ 4027.799162] 7fa0:                                     00000000 00000000 00000013 13aa538a
[ 4027.807381] 7fc0: 13aa538b 00000000 00000014 bea5d7a8 1f400000 00000000 00000000 00000000
[ 4027.815597] 7fe0: fffffff4 bea5d77c 0000000c b6da6e80 800f0030 ffffffff
[ 4027.822257] ---[ end Kernel panic - not syncing: Fatal exception in interrupt ]---

How solve this problem?
Thanks 
Regards

**Comment by jypan-ccu** [comment]
Try the new pull request, or try the code in https://github.com/jypan-ccu/ldd3.git

**Comment by dwalkes** [comment]
@jisu5619 please let me know if this is resolved with the latest master merge

**Comment by dwalkes** [comment]
Assuming this is resolved, please reopen if not.
