### ISSUE TITLE
Return value of cdev_add() in ldd3/scullp/main.c

### ISSUE THREAD

**Issue by YSL-1997** [martinezjavier/ldd3#63]
This is my first time posting an issue. If I made any inappropriate mistakes, please correct me. Thanks in advance.

On [line 454 of scullp/main.c](https://github.com/martinezjavier/ldd3/blob/6657e96a0273f21f22d9d8c46976839c923b45d7/scullp/main.c#L454), the return value of ```cdev_add()``` is assigned to ```err```, which is then evaluated by the if-condition. According to [API](https://www.kernel.org/doc/htmldocs/kernel-api/API-cdev-add.html) of ```cdev_add()```, it returns a negative error code on failure; hence, if it fails, then ```err``` will be assigned a negative value, which means the error message will never be printed. Could anyone please tell me what the purpose of this is? Thanks in advance.

**Comment by Minoru** [comment]
Hi! That's a perfectly valid question ;)

In C, e.g. in an `if` operator, zero is considered to be "false", and *anything else* is considered to be "true" — including negative values. So the error message is shown when `err` is not zero, which is the intended effect.

**Comment by YSL-1997** [comment]
Thanks a lot for your clarification :). I am sorry that I did not fully understood such basic concept of ```if``` condition.

Since this issue has been fixed, I would like to close this issue.
