### ISSUE TITLE
Errors while compiling => In jit.c

### ISSUE THREAD

**Issue by zoe9216** [martinezjavier/ldd3#77]
Was trying to `make` from directory `ldd3`. However, I got the following errors:
`In function ‘jit_fn_open’:
/home/meraj_hasan/ldd3/misc-modules/jit.c:96:40: error: implicit declaration of function ‘PDE_DATA’; did you mean ‘NODE_DATA’? [-Werror=implicit-function-declaration]
   96 |  return single_open(file, jit_fn_show, PDE_DATA(inode));
      |                                        ^~~~~~~~
      |                                        NODE_DATA
/home/meraj_hasan/ldd3/misc-modules/jit.c:96:40: error: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [-Werror=int-conversion]
   96 |  return single_open(file, jit_fn_show, PDE_DATA(inode));
      |                                        ^~~~~~~~~~~~~~~
      |                                        |
      |                                        int
In file included from /home/meraj_hasan/ldd3/misc-modules/jit.c:26:
./include/linux/seq_file.h:166:68: note: expected ‘void *’ but argument is of type ‘int’
  166 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
/home/meraj_hasan/ldd3/misc-modules/jit.c: In function ‘jit_tasklet_open’:
/home/meraj_hasan/ldd3/misc-modules/jit.c:306:45: error: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [-Werror=int-conversion]
  306 |  return single_open(file, jit_tasklet_show, PDE_DATA(inode));
      |                                             ^~~~~~~~~~~~~~~
      |                                             |
      |                                             int
In file included from /home/meraj_hasan/ldd3/misc-modules/jit.c:26:
./include/linux/seq_file.h:166:68: note: expected ‘void *’ but argument is of type ‘int’
  166 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:250: /home/meraj_hasan/ldd3/misc-modules/jit.o] Error 1
make[2]: *** [Makefile:1992: /home/meraj_hasan/ldd3/misc-modules] Error 2
make[2]: Leaving directory '/home/meraj_hasan/linux'
make[1]: *** [Makefile:20: modules] Error 2
make[1]: Leaving directory '/home/meraj_hasan/ldd3/misc-modules'
make: *** [Makefile:10: subdirs] Error 1`

How do I fix these? Earlier I had to do `make oldconfig` and `make prepare` in `linux` directory as some files were missing.

**Comment by scshafe** [comment]
try replacing 'PDE_DATA' with 'pde_data' in all instances.

**Comment by martinezjavier** [comment]
Fixed by PR #78.
